=== avasiljeva/lab02-meetings/lab02-meetings-core/src/main/resources/data/users.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xsd:element name="users" type="usersType"/>
    <xsd:complexType name="usersType">
        <xsd:sequence maxOccurs="unbounded">
            <xsd:element name="user" type="userType"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="userType">
        <xsd:sequence>
        	<xsd:element name="first-name" type="xsd:string"/>
        	<xsd:element name="last-name" type="xsd:string"/>
            <xsd:element name="username" type="xsd:string"/>
            <xsd:element name="password" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== avasiljeva/lab02-meetings/lab02-meetings-core/src/main/resources/data/users.xml
<?xml version="1.0" encoding="UTF-8"?>
<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		xsi:noNamespaceSchemaLocation="src\main\resources\data\users.xsd">
    <user>
        <first-name>John</first-name>
        <last-name>White</last-name>
        <username>jwhite</username>
        <password>jwhite</password>
    </user>
    <user>
        <first-name>David</first-name>
		<last-name>Green</last-name>
        <username>dgreen</username>
        <password>dgreen</password>
    </user>
    <user>
        <first-name>Ann</first-name>
		<last-name>Blue</last-name>
        <username>ablue</username>
        <password>ablue</password>
    </user>
    <user>
        <first-name>Max</first-name>
		<last-name>Black</last-name>
        <username>mblack</username>
        <password>mblack</password>
    </user>
    <user>
        <first-name>Ketty</first-name>
		<last-name>Purple</last-name>    
        <username>kpurple</username>
        <password>kpurple</password>
    </user>      
</users>
